name: test
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: install golang dependencies
      run: go mod tidy
    - name: lint and build
      run: PATH=$PATH:$HOME/go/bin ./build.sh
    - name: run
      run: ./bin/ldpmarc -h

